import Link from "next/link";
import { notFound } from "next/navigation";
import { getDemoFixture } from "@/lib/demo-data";
import { DemoDraftFollowUp } from "@/components/demo-draft-followup";
import { RISK_META, formatMoney, relativeDays, riskTier } from "@/lib/ui/risk";

function IntelligenceList({ label, items }: { label: string; items?: string[] }) {
  if (!items || items.length === 0) return null;
  return (
    <div>
      <p className="mb-1 text-xs font-medium text-slate-500">{label}</p>
      <ul className="flex flex-col gap-1">
        {items.map((item) => (
          <li key={item} className="text-sm text-slate-300">
            • {item}
          </li>
        ))}
      </ul>
    </div>
  );
}

export default async function DemoClientDetailPage({
  params,
}: {
  params: Promise<{ id: string }>;
}) {
  const { id } = await params;
  const fixture = getDemoFixture(id);
  if (!fixture) notFound();

  const { row, contactEmail, draft, analyzedYet } = fixture;
  const client = row.clients!;
  const tier = riskTier(row.health_score);
  const meta = RISK_META[tier];
  const lastContactAt = client.threads[0]?.last_message_at ?? null;
  const intelligence = Array.isArray(client.client_intelligence)
    ? client.client_intelligence[0]
    : client.client_intelligence;
  const extraction = intelligence?.extraction_json ?? null;

  return (
    <main className="min-h-screen bg-[#0a0e17] px-6 py-10 text-slate-100">
      <div className="mx-auto flex max-w-2xl flex-col gap-6">
        <div className="flex items-center justify-between">
          <Link href="/demo" className="text-sm text-slate-400 hover:text-slate-200">
            ← Back to demo dashboard
          </Link>
          <Link href="/" className="rounded-md border border-slate-700 px-3 py-1.5 text-xs text-slate-300 hover:bg-slate-800">
            Connect Gmail
          </Link>
        </div>

        <div className="animate-fade-in-up rounded-lg border border-amber-900/40 bg-amber-400/5 px-4 py-3 text-sm text-amber-200">
          Sample data — this client isn&apos;t real.
        </div>

        <div>
          <h1 className="text-2xl font-semibold text-slate-100">{client.name}</h1>
          <p className="text-sm text-slate-500">{client.email_domain}</p>
        </div>

        <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
          <section className="rounded-lg border border-slate-800 bg-slate-900/60 p-5">
            <h2 className="mb-1 text-xs font-medium uppercase tracking-wide text-slate-500">Relationship health</h2>
            <span className={`inline-flex items-center gap-1 rounded-full px-2 py-0.5 text-xs font-medium ${meta.badgeBg} ${meta.text}`}>
              {meta.emoji} {meta.label}
            </span>
            <p className="mt-2 text-sm text-slate-400">Last contact: {relativeDays(lastContactAt)}</p>
            {row.dollar_at_risk ? (
              <p className="mt-1 text-sm text-red-300">{formatMoney(row.dollar_at_risk)} at risk</p>
            ) : null}
          </section>

          <section className="rounded-lg border border-slate-800 bg-slate-900/60 p-5">
            <div className="flex items-center justify-between">
              <h2 className="text-xs font-medium uppercase tracking-wide text-slate-500">Suggested next action</h2>
              {row.top_reasons_json?.confidence && (
                <span className="text-xs text-slate-500">
                  Confidence: <span className="text-slate-300">{row.top_reasons_json.confidence}</span>
                </span>
              )}
            </div>
            <p className="mt-1 text-xs text-slate-600">
              Calculated from reply timing, volume, and thread activity — not AI.
            </p>
            <p className={`mt-2 text-sm font-medium ${meta.text}`}>{row.top_reasons_json?.suggestedAction}</p>
          </section>
        </div>

        <section className="animate-fade-in-up rounded-lg border border-slate-800 bg-slate-900/60 p-5">
          <h2 className="mb-1 text-xs font-medium uppercase tracking-wide text-slate-500">Conversation intelligence</h2>
          {!extraction ? (
            <p className="text-sm text-slate-500">
              Not analyzed yet — click <strong>Analyze conversations</strong> on the{" "}
              <Link href="/demo" className="underline underline-offset-2">
                demo dashboard
              </Link>{" "}
              to have Claude read this relationship&apos;s recent emails for objections, buying
              signals, and open questions.
            </p>
          ) : (
            <>
              <p className="mb-3 text-xs text-slate-600">
                AI-generated by Claude, based on this client&apos;s recent conversations.
              </p>
              {intelligence?.summary && <p className="mb-3 text-sm text-slate-300">{intelligence.summary}</p>}
              <div className="grid grid-cols-1 gap-3 sm:grid-cols-2">
                <IntelligenceList label="Open questions" items={extraction.open_questions} />
                <IntelligenceList label="Objections" items={extraction.objections} />
                <IntelligenceList label="Buying signals" items={extraction.buying_signals} />
                <IntelligenceList label="Hesitation signals" items={extraction.hesitation_signals} />
                <IntelligenceList label="Pricing mentions" items={extraction.pricing_mentions} />
                <IntelligenceList label="Competitor mentions" items={extraction.competitor_mentions} />
              </div>
              {extraction.commitments.length > 0 && (
                <div className="mt-3">
                  <p className="mb-1 text-xs font-medium text-slate-500">Commitments</p>
                  <ul className="flex flex-col gap-1">
                    {extraction.commitments.map((c, i) => (
                      <li key={i} className="text-sm text-slate-300">
                        {c.by === "user" ? "You" : "They"} said: &ldquo;{c.text}&rdquo;
                        {c.fulfilled === false && <span className="ml-1 text-amber-400">— not yet fulfilled</span>}
                        {c.fulfilled === true && <span className="ml-1 text-emerald-400">— fulfilled</span>}
                      </li>
                    ))}
                  </ul>
                </div>
              )}
            </>
          )}
        </section>

        <DemoDraftFollowUp draft={analyzedYet ? draft : { canDraft: false, reason: "Not analyzed yet in this demo." }} />

        <p className="text-xs text-slate-600">Contact on file: {contactEmail}</p>
      </div>
    </main>
  );
}
